### ISSUE TITLE
add and enable arprefresh plugin by default

### ISSUE THREAD

**Issue by vchrizz** [vchrizz/ER-wizard-OLSRd_V1#16]
from [README_ARPREFRESH](https://github.com/OLSR/olsrd/blob/master/lib/arprefresh/README_ARPREFRESH):

The plugin listens to all received UDP packets on port 698 and maintains
an internal list of MAC addresses extracted from these. The kernel ARP
cache will be refreshed from this list if a direct-neighbor host route is
configured. Result: no more ARP lookups if you use a larger routing
chain - e.g. fetch a web site 8 olsr-hops away does not show the typical
8-nodes-need-to-ARP first delay.
IPv4 only.
Does not support VLANs.

add in /etc/olsrd/olsrd.conf:

LoadPlugin "olsrd_arprefresh.so.0.1"
{
}

**Comment by pocki80** [comment]
plugin can be enabled/disabled in wizard version 0903repacked. enable by default is not implemented
