### ISSUE TITLE
Include timestamp in 0xffolsrd.log

### ISSUE THREAD

**Issue by schulti** [vchrizz/ER-wizard-OLSRd_V1#19]
Hi guys,

I'm troubleshooting a possible problem and don't find timestamps in the logfiles. Maybe this can be added easily? 

Danke! 
LgS

**Comment by pocki80** [comment]
Logfile entries from wizard-run (triggered from web-ui) should contain timestamps already, starting with "starting wizard" to "ended wizard". 
Can you please report a logfile entry where you are missing a time stamp?

**Comment by schulti** [comment]
Find attached example.

[timeless-0xffolsrd.log](https://github.com/vchrizz/ER-wizard-OLSRd_V1/files/1834616/timeless-0xffolsrd.log)

**Comment by pocki80** [comment]
I see, looks like an old installation log from dpgk-i followed by starting procedures of olsrd and olsrd6. I will try to add timestamps for these procedures.
Anyway, you can look after /tmp/olsrd.log for start/stop/crash of olsrd (ipv4 instance). mybe that helps for now.
