### ISSUE TITLE
[enhancement] define which routing table to use

### ISSUE THREAD

**Issue by 1-am-r00t** [vchrizz/ER-wizard-OLSRd_V1#21]
I stumbled upon this due to initial configuration of WAN load-balancing with 0xFF as primary uplink and LTE as backup/failover-only.
By default OLSRd appends the "learned" routes from OLSR to the table `main` - in my case it was necessary to append them to table `201`, as the load-balancing mechanism of EdgeMax by default creates an unique table per specified interface in the load-balancing group.
For the mechanism to work (mainly due to the default-route), it is necessary to define in `olsrd.conf`, which routing table OLSRd should append the routes to.
I now set the parameter `RtTableDefault 201` manually in `/config/user-data/olsrd4.conf`, but it would be quite convenient to have something like an input textfield with the remark "specify which routing table OLSRd to use. default: [main]". Mainly because it could be a problem when the user changes something in the Wizard as the manual changes will be overwritten.

Reference can be found in the links below and in the attached files (routing-tables, load-balancing config).

Please feel free to contact me any time if there are any questions!

[erx.txt](https://github.com/vchrizz/ER-wizard-OLSRd_V1/files/2898183/erx.txt)
http://www.olsr.org/?q=node/51
https://community.ubnt.com/t5/EdgeRouter/How-does-the-firewall-action-modify-operate-or-work/td-p/2324592
https://community.ubnt.com/t5/EdgeRouter/How-to-Set-Up-Wan-Failover-with-Edgemax-1-4-0-and-Edgerouter-POE/td-p/714073
https://help.ubnt.com/hc/en-us/articles/205145990-EdgeRouter-WAN-Load-Balancing

**Comment by pocki80** [comment]
I added a section "OLSRD IPv4 Advanced", please try this wizard - this is a testing! version for a mostly re-written wizard, so it does much more than just adding this RtProto management function. So I recomend to test this install/update on a non-productive router or a router which you easily can wipe olsrd from and then reinstall the older/previous build.

My private tests were all fine, so I feel pretty good about it.
[ER-wizard-OLSRd_V1-0903repacked.tar.gz](https://github.com/vchrizz/ER-wizard-OLSRd_V1/files/2919269/ER-wizard-OLSRd_V1-0903repacked.tar.gz)

**Comment by pocki80** [comment]
Forget about 0.9.0.3 - I managed to add the most current commit of 0.9.6.2 (aka pre-0.9.7). This includes bugfixes for the info-plugins (maybe we no more suffer from continues crashes?) and the "silent" interface mode.

Here's a wizard version to test upgrading, installing and olsrd itself:

[ER-wizard-OLSRd_V1-0962repacked.tar.gz](https://github.com/vchrizz/ER-wizard-OLSRd_V1/files/2926790/ER-wizard-OLSRd_V1-0962repacked.tar.gz)

**Comment by pocki80** [comment]
I released v3.0 of this wizard, aka Version "0962r68/20190309". It can be downloaded from this release or the master branch - or you upgrade your EdgeRouter from the previous WizardUI using the "Upgrade from Github on Apply" function.
AutoUpdate to this version will be enabled later on...
