### ISSUE TITLE
option for ebtables to DROP FORWARD

### ISSUE THREAD

**Issue by schulti** [vchrizz/ER-wizard-OLSRd_V1#7]
Hi guys,

thank you for the great work on the Wizard!

By default it's turned off to FORWARD layer-2 packets via ebtables. But in some cases this is wanted.

Can you please add an option to the webinterface to allow packets in ebtables' FORWARD queue. Maybe this option could be kept/stored over updates?

Thank you!

LgS

**Comment by pocki80** [comment]
A separate wizard (meant as add on for olsrd-v1 wizard) is progress: https://github.com/pocki80/ER-wizard-ebtables

**Comment by pocki80** [comment]
https://github.com/pocki80/ER-wizard-ebtables v0.2 is a working release for this
